# build stage
FROM node:18.17.0 AS build
WORKDIR /app
COPY web/package*.json ./web/
RUN rm -rf ./web/node_modules && yarn install
COPY web/ ./
RUN yarn build

# depoly stage
FROM node:18.17.0
WORKDIR /app
COPY --from=build /app/web/build/ ./build/
RUN yarn global add serve
EXPOSE 8080
CMD ["serve", "-p", "8080", "build/"]