FROM node:18.17.0

WORKDIR /app

COPY web/package*.json ./web/

WORKDIR /app/web

# 移除現有node_modules 目錄
RUN rm -rf ./web/node_modules

RUN yarn install

WORKDIR /app

COPY web/ ./

RUN yarn build

EXPOSE 3000

CMD [ "yarn", "start" ]

# RUN yarn global add serve

# CMD ["serve", "-s", "build", "-l", "3000"]
